daemon off;
error_log logs/error.log debug;
pid logs/nginx.pid;

events {
    worker_connections 64;
}

http {
    js_engine qjs;
    js_path "njs/";

    js_import main from app.js;

    server {
        listen 8888;

        location /describe {
            js_content main.describe;
        }

        location /emit-demo {
            js_content main.emit_demo;
        }

        location /emit-statsd {
            js_content main.emit_statsd;
        }

        location /emit-dogstatsd {
            js_content main.emit_dogstatsd;
        }

        location /validate {
            js_content main.validate_metric;
        }

        location /describe-metric {
            js_content main.describe_metric;
        }

        location /emit-helper {
            js_content main.emit_helper;
        }
    }
}
